# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wpM_8aDg3Be8idHpmPfZR1SB8d9F9ywN
"""

def df2d_to_array3d(df_2d):
  
    # 입력 받은 2차원 데이터 프레임을 3차원 numpy array로 변경하는 함수
    feature_size = df_2d.iloc[:,2:].shape[1]
    time_size = len(df_2d.time.value_counts())
    sample_size = len(df_2d.sample_id.value_counts())
    array_3d = df_2d.iloc[:,2:].values.reshape([sample_size, time_size, feature_size])
    return array_3d

def load_data(df2d_to_array3d=df2d_to_array3d):   #이게 안되면 class로 바꿔서 하는 것도 방법일 듯. 
  
  import torch
  import pandas as pd
  
  data_path='/content/drive/MyDrive/Colab Notebooks/Bitcoin_Trading/data'

  # 데이터 가져오기
  train_x_df = pd.read_csv(data_path  + "/train_x_df.csv")
  train_y_df = pd.read_csv(data_path  + "/train_y_df.csv")

  train_x_df=train_x_df.drop(['volume', 'quote_av','trades','tb_base_av','tb_quote_av'], axis=1)
  train_y_df=train_y_df.drop(['volume', 'quote_av','trades','tb_base_av','tb_quote_av'], axis=1)

  # 2d to 3d  array로 바꾸기
  train_x_array = df2d_to_array3d(train_x_df) #(7362, 1380, 5)
  train_y_array = df2d_to_array3d(train_y_df) #(7362, 120, ,5)

  train_x_array=torch.from_numpy(train_x_array)
  train_y_array=torch.from_numpy(train_y_array)

  return train_x_array, train_y_array